### ISSUE TITLE
Avoid parsing the font twice if I’m using ttf_parser directly 

### ISSUE THREAD

**Issue by asibahi** [alexheretic/ab-glyph#102]
Hello

I cannot actually tell if this is already possible or not. If I have another dependency on ttf_parser (say for/through rustybuzz which reexports it), is it possible to avoid parsing the font twice (once through rustybuzz and once through ab_glyph)?

**Comment by alexheretic** [comment]
I don't think this is possible at the same time as avoiding breaking semver for each ttf-parser break. I believe ttf-parser font parsing is also fairly cheap.
