### ISSUE TITLE
Support for TrueType collections (`.ttc`)

### ISSUE THREAD

**Issue by abrisco** [alexheretic/ab-glyph#106]
Is it possible to load a [TrueType collection](https://en.wikipedia.org/wiki/TrueType#Collection) (`.ttc` file)? A quick search search didn't reveal anything so thought I'd ask 😄.

Also, thank you for this library!

**Comment by alexheretic** [comment]
I haven't really built in much support for them as I never had need to use one myself. But I believe they should work, you can parse a font in one using its index with [`FontRef::try_from_slice_and_index`](https://docs.rs/ab_glyph/latest/ab_glyph/struct.FontRef.html#method.try_from_slice_and_index).

**Comment by abrisco** [comment]
That works, thank you so much!
