### ISSUE TITLE
How to get glyph advance_width and advance_height (by used for layout)?

### ISSUE THREAD

**Issue by TakWolf** [alexheretic/ab-glyph#12]
If layout horizontal and from left to right:

advance_height = px_scale_font.ascent() - px_scale_font.descent(); // 
advance_width = ?

![image](https://user-images.githubusercontent.com/6064962/88629913-71e15300-d0e2-11ea-93cc-9a7a49a96906.png)

image ref from https://github.com/alexheretic/ab-glyph/issues/6

**Comment by alexheretic** [comment]
You mean the [`h_advance`](https://docs.rs/ab_glyph/0.2.5/ab_glyph/trait.ScaleFont.html#method.h_advance)?

**Comment by TakWolf** [comment]
I found these:

px_scale_font.v_advance();
px_scale_font.h_advance();
px_scale_font.height(); // Pixel scaled height `ascent - descent`.

v_advance and h_advance are fixed value in a font, should them used for layout?

I refer to rusttype layout example:
https://github.com/redox-os/rusttype/blob/master/dev/examples/gpu_cache.rs#L12-L51
```rust 
    let advance_height = v_metrics.ascent - v_metrics.descent + v_metrics.line_gap;
....
        caret.x += glyph.unpositioned().h_metrics().advance_width;
```

**Comment by TakWolf** [comment]
My pseudocode :

```
let font = FontRef::new();
let font_size = 24;
let px_scale_font = font.as_scaled(font_size);
let crate = (0, 0);
for c in text.chars() {
    if c == '\n' {
         crate.x = 0;
         crate.y += px_scale_font. h_advance();  // or px_scale_font.height()?  or px_scale_font.ascent() - px_scale_font.descent() + px_scale_font.line_gap() ?
    } else {
          let outlined_glyph = xxx;
          crate.x += outlined_glyph.w_advance(); // <---- I think it should be here. or glyph.w_advance();
    }
}
```

**Comment by alexheretic** [comment]
A simple layout example similar to rusttype's example code is used for benchmarks: https://github.com/alexheretic/ab-glyph/blob/master/dev/src/layout.rs

There's also [glyph_brush_layout](https://github.com/alexheretic/glyph-brush/tree/master/layout) for more advanced stuff.
