### ISSUE TITLE
How to get the no glyph placeholder rasterize drawable?

### ISSUE THREAD

**Issue by TakWolf** [alexheretic/ab-glyph#13]
like this:
![image](https://user-images.githubusercontent.com/6064962/88631936-883cde00-d0e5-11ea-9c5b-26438c8f4697.png)

**Comment by alexheretic** [comment]
Some fonts have a outline for their `FontId(0)` unsupported glyphs I think, but most of the ones I use will just render nothing. Maybe other programs render their own placeholder outline based on the glyph position & dimensions?

**Comment by TakWolf** [comment]
I get it. Thank you.

I try `font.glyph_id('\0')`, it is effective in some fonts.
