### ISSUE TITLE
Provide benchmarks against rusttype

### ISSUE THREAD

**Issue by JAicewizard** [alexheretic/ab-glyph#17]
As this is a direct descendant of rusttype, and a continuation of that project aimed at solving, in part, performance it would be nice to see some common cases where performance will have increased (or decreased!!).
These might not be perfect since the API changed, but they should be an indication of common operations like rendering some text.

EDIT: I didnt look closely enough, but maybe put the benchmarks in the repo readme.md as well, thats where people will often look for them.

Anyway, looks like a nice performance bump you got from doing the revamp!

**Comment by alexheretic** [comment]
Yep a simple comparison is provided in the [ab_glyph nested readme](https://github.com/alexheretic/ab-glyph/tree/master/glyph#comparison-with-rusttype). 

Maybe it'll be worth just hoisting this readme to the root level and having a link to a nested one just for ab_glyph_rasterizer? The nested readme is used on [crates.io/crates/ab_glyph](https://crates.io/crates/ab_glyph), so maybe it isn't a big deal.

I don't expect ab_glyph to be slower that rusttype at anything really. They're fairly similar abstractions on ttf-parser, but ab_glyph does less implicitly, so no font-ref cloning or pixel bounding box calculating unless asked for explicitly. The latter particularly matters for otf fonts.

**Comment by alexheretic** [comment]
I'll assume it isn't a huge deal having ab_glyph readme top level.
