### ISSUE TITLE
Returning partially clipped glyphs

### ISSUE THREAD

**Issue by chinedufn** [alexheretic/ab-glyph#20]
Last I checked a year ago, if a glyph was partially outside of the bounds for the text section it would not be included when calling process_queued.

I’d like to be able to instead have these partially clipped glyphs returned, with the glyph’s texture and size bounds adjusted to only encompass the part that is within the text bounds.

This would make things such as scrolling windows easier as you wouldn’t need to handle partial clipping at the edges when scrolling yourself.

Would there be any downsides to this design? I can’t think of any but I’m not familiar with the reason that it isn’t done that way currently.

Thanks!

**Comment by alexheretic** [comment]
I think this isn't relevant to ab_glyph, this lib doesn't provide any concept of sections or layout.

For glyph_brush_layout it already does this vertically, for multi-line layouts it doesn't allow horizontal partial glyphs, which is kind of the job of a paragraph algorithm. For single line layouts you _can_ have horizontal overlap too. Raise an issue in https://github.com/alexheretic/glyph-brush if you'd like to discuss those.

**Comment by chinedufn** [comment]
Wow I actually thought I opened this in glyph brush, sorry!

**Comment by chinedufn** [comment]
All I need is vertical so I’m good to go thanks!
