### ISSUE TITLE
please include license text in published crates

### ISSUE THREAD

**Issue by decathorpe** [alexheretic/ab-glyph#23]
The ab_glyph and ab_glyph_rasterizer crates that get produced and uploaded to crates.io don't include the license text for your specified license - however, the Apache 2.0 license usually requires that you ship the text alongside the licensed material (see "License and Copyright notice" [here]).

Can you please include the license text in the published crates? If you're `cargo publish`ing from linux/macos, adding a symlink `LICENSE → ../LICENSE` in both directories should be enough to accomplish this (since you're not `exclude`ing anything in Cargo.toml).

EDIT: Forgot to actually link the thing I wanted to link to [here].

[here]: https://choosealicense.com/licenses/apache-2.0/

**Comment by alexheretic** [comment]
I didn't think this was necessary, it's a bit annoying to have to copy the license to each subdirectory (git has no symlinks).

Do you have some references to other cargo workspace style projects that addressed this without license duplication?

**Comment by decathorpe** [comment]
git does support symlinks. For example, the futures crate does it this way:
https://github.com/rust-lang/futures-rs/tree/master/futures-core

**Comment by alexheretic** [comment]
TIL, ok that sounds fine then, thanks for the example. I'll add the
symlinks when I get a chance.

**Comment by decathorpe** [comment]
Thanks!
