### ISSUE TITLE
Is Fontdue faster than ab-glyph?

### ISSUE THREAD

**Issue by Tizoner** [alexheretic/ab-glyph#25]
https://github.com/mooman219/fontdue

**Comment by alexheretic** [comment]
Maybe, and indeed maybe some lessons there can be applied to ab-glyph. I don't have any plans to pursue that myself currently. However, if you have optimisations in mind please raise issues/prs. My own thoughts about future text performance work are more at the _draw-cache_ & _glyph-brush_ level at the moment, but I'm not sure when I'll get round to even that.

If you're wondering which crate you should use, my advice would be to run your own tests and use whatever works best for you.
