### ISSUE TITLE
Documentation on glyph_bounds Unclear

### ISSUE THREAD

**Issue by anlumo** [alexheretic/ab-glyph#31]
The documentation for Font::glyph_bounds says

    /// Returns the layout bounds of this glyph. These are different to the outline `px_bounds()`.
    ///
    /// Horizontally: Glyph position +/- h_advance/h_side_bearing.
    /// Vertically: Glyph position +/- ascent/descent.

As someone with no formal typesetting education, I don't know what this text is trying to tell me. So, the result is different to `px_bounds`, but how? Why?

I'm currently trying to use this function, but the result cuts off the text on the left and right. I guess this comment is supposed to explain why, but it's a mystery to me.

Frankly, this feels like a quick note by the author of that code to themselves, rather than something others should be able to interpret. Could you expand on that definition?

**Comment by alexheretic** [comment]
`glyph_bounds` are calculated from the font layout values, like advance. They work for pretty much any glyph. Those docs seem to define it pretty well as far as I can see.

`h_advance`, `h_side_bearing`, `ascent` & `descent` are all methods & use existing font terminology. Yes, currently it looks like you just need to know what these mean or work it out from examples. I'd welcome improvements to the docs.

Image support in rust docs would be quite helpful though...
![](https://camo.githubusercontent.com/9c8ff61864a00693ebed05bbda02a7c1646c750f52656133b71685cd31a301c6/68747470733a2f2f61736b2e656d6265646465642d77697a6172642e64652f3f71613d626c6f622671615f626c6f6269643d3137323237343530343631303132303336333834)

The outline `px_bounds` are the _"conservative whole number pixel bounding box"_ for an `OutlinedGlyph`. So they only exist for glyphs with an outline. It's more of a drawing concept that's needed when you're interested in rasterizing the glyphs into a pixel grid.

So, for example, a monospace font at a given scale will have uniform `Font::glyph_bounds`, but each glyph will probably have different outlines and so different `OutlinedGlyph::px_bounds`.

I'd guess your cut off text bug may have a different cause.

**Comment by anlumo** [comment]
I analyzed the implementation of `px_bounds` and found [here](https://github.com/alexheretic/ab-glyph/blob/433e1ba8178f72fd5ca483b08d0e41250034157a/glyph/src/ttfp/bbox.rs#L46) that it just takes all points used in the path and calculates the bounding box based on those. When I do the same thing myself, it works out to be correct. I guess if you want to implement text selection highlighting, the `glyph_bounds` rectangle is more interesting.

The background is that I'm currently trying to move from the integrated rasterizer to a different one (HTML canvas via web-sys), so I have to reimplement all these pixel-based calculations.

**Comment by alexheretic** [comment]
That px_bounds calculation is just a fallback for malformed fonts. Generally the bbox is returned from _ttf-parser_ as part of outlining the glyph.

Can you elaborate on why you can't use `px_bounds` and `draw`. Outlining & drawing in _ab_glyph_ isn't render API specific in any way. `draw` just tells you what alpha to set at a given coordinate.

**Comment by anlumo** [comment]
> That px_bounds calculation is just a fallback for malformed fonts. Generally the bbox is returned from _ttf-parser_ as part of outlining the glyph.

How can I access this information from the outside?

> Can you elaborate on why you can't use `px_bounds` and `draw`. Outlining & drawing in _ab_glyph_ isn't render API specific in any way. `draw` just tells you what alpha to set at a given coordinate.

I have to render a text outline like this:
![image](https://user-images.githubusercontent.com/644763/107865420-5400f300-6e66-11eb-9bfc-e2f754487129.png)

Unless I implement some kind of pixel filter (tried that, it's problematic), I need the actual path outline, so I can stroke the path before filling it.

**Comment by alexheretic** [comment]
Right ok, so you want the outline. I would have thought you'd be using the `Font::outline` method then. 

An [`Outline`](https://docs.rs/ab_glyph/0.2.9/ab_glyph/struct.Outline.html) comes with the bounds & it's own `px_bounds` method for scaling, so you don't need to work them out again.

**Comment by anlumo** [comment]
Oh, I somehow missed that function. Works and is much cleaner, thank you!

**Comment by alexheretic** [comment]
I don't this we have any more actions to take from this issue, so I'll close. Please let me know otherwise.
