### ISSUE TITLE
Hit panic!("Invalid bounding box from Face::outline_glyph")

### ISSUE THREAD

**Issue by danieldg** [alexheretic/ab-glyph#32]
I was able to hit this panic when trying to draw code points 0x2001..0x2004 from Symbola.ttf (https://fedoraproject.org/wiki/Gdouros_Symbola).  These code points are all whitespace of some kind, so I suspect (but have not verified) that the bounding box has a zero-size dimension.

https://github.com/alexheretic/ab-glyph/blob/cb8241d2e9ce89b29717e8780c91b9ceb2fecfd8/glyph/src/ttfp.rs#L253

**Comment by alexheretic** [comment]
This panic means one of the glyphs bounding box calculated by _ttf-parser_ is invalid. This tends to suggest the font is erroneous and/or _ttf-parser_ is not accounting for that. I'd expect whitespace fonts to not return any outline bounding box.

Can you provide a link to the font ttf? I can't provide upstream with decent steps to reproduce this without that, I can't figure out how to get it from the links you have provided.

**Comment by danieldg** [comment]
https://kojipkgs.fedoraproject.org//packages/gdouros-symbola-fonts/10.24/8.fc34/src/gdouros-symbola-fonts-10.24-8.fc34.src.rpm is the RPM containing it; I couldn't figure out how to link just the file but its info page is: https://koji.fedoraproject.org/koji/fileinfo?rpmID=24696399&filename=/usr/share/fonts/gdouros-symbola/Symbola.ttf
