### ISSUE TITLE
GPU Caching

### ISSUE THREAD

**Issue by zedseven** [alexheretic/ab-glyph#43]
I was originally looking at going with rusttype, but I found this and it looks like it might suit my needs better (it's also actively maintained).

The one thing that concerns me is GPU caching - this seems to be something this crate is missing compared to rusttype, and I was wondering a couple of things:
- Do you have plans to implement this in the future?
- Have I just missed or misunderstood something? Is there a reason why it isn't included yet?

My use case involves potentially rendering new text every frame, which is why it's a feature I'm interested in.

Thanks for your work on this crate as well as your work maintaining rusttype - I appreciate it.

**Comment by alexheretic** [comment]
It was my opinion that the draw caching logic should have been a separate crate in _rusttype_, so it is for _ab_glyph_ have a look at [glyph_brush_draw_cache](https://github.com/alexheretic/glyph-brush/tree/master/draw-cache). 

This crate is focussed on the _glyph_brush_ use case, which is where I use it. However, it currently still has a very similar API to rusttype's gpu_cache module. You also may find _glyph_brush_ itself useful for text rendering.

**Comment by zedseven** [comment]
That does make sense.

Thank you for your prompt response!
