### ISSUE TITLE
provide alternative to Font::glyph_id for specifying glyphs for whom no char exists

### ISSUE THREAD

**Issue by neadeer** [alexheretic/ab-glyph#44]
i would like to use ab-glyph with a font-shaping library, like harfbuzz.

ab-glyph is great for writing-systems with nice char->glyph mappings, but many writing systems have glyphs that are effected by the surrounding text or glyphs that are composed of multiple char.

if there was some way of feeding a glyph id as an integer value, i could ask my font-shaping library what glyph i need, and ab-glyph could render it for me.

**Comment by alexheretic** [comment]
If you know the integer id you don't need to call `Font::glyph_id`, you can construct directly

```rust
GlyphId(123).with_scale(48.0)
```

**Comment by neadeer** [comment]
thanks!
