### ISSUE TITLE
Embedding fonts at compile time

### ISSUE THREAD

**Issue by LoganDark** [alexheretic/ab-glyph#54]
I think there should be a proc macro or a const fn or something we can use to embed a `Font` directly in the binary such that error handling doesn't have to be performed at runtime (no possibility of a panic). Would be nice for embedded applications

**Comment by alexheretic** [comment]
You can embed a font with `include_bytes!`. But, indeed, it will need to be parsed at runtime. _ttf-parser_ doesn't provide `const fn` to parse fonts, though perhaps that's possible. _ttf-parser_ already avoids allocation by parsing stuff on the fly during the various method calls anyway, so I'm not sure there would be too much benefit in avoiding the initial bit.
