### ISSUE TITLE
Cantarell rendered with black boxes

### ISSUE THREAD

**Issue by treetertot** [alexheretic/ab-glyph#57]
My repository https://github.com/treetertot/cantarell_test demonstrates an issue in how ab_glyph renders Cantarell. There are large rectangles over many of the letters that do not appear when rendered by gtk.

I've cloned ab_glyph and am still tracking down the exact problem myself.

**Comment by alexheretic** [comment]
Thanks! It seems the font glyph outlines implicitly "close" and we weren't doing that. I've added that in #58.

**Comment by treetertot** [comment]
Oh great! That fixed it
