### ISSUE TITLE
Subpixel Antialiasing

### ISSUE THREAD

**Issue by markusmoenig** [alexheretic/ab-glyph#60]
Hi,

great job, any plans to support sub pixel AA ? At small resolutions and low contrast things can get ugly. Would be great if we would have better AA support one day.

Thanks!

**Comment by alexheretic** [comment]
Hello, the short answer is I don't have any such plans personally. I find the regular pixel coverage AA to work well at the resolutions I target. However, I would be interested in the results were someone to investigate it.

The lib also does not support hinting. Perhaps using freetype or equivalent native libs would be the choice for low resolution rendering?

**Comment by markusmoenig** [comment]
Ok, thanks for the answer Alex.
