### ISSUE TITLE
Setting font variations

### ISSUE THREAD

**Issue by NathanRoyer** [alexheretic/ab-glyph#61]
Hello,

First of all, thanks for `ab_glyph` and `glyph_brush`; `ab_glyph` is what's used to render glyphs in my [`acrylic`](https://lib.rs/acrylic) crate.

I was wondering how I could configure a font's variations?
I see that `ttf-parser` has a [`Face::set_variation`](https://docs.rs/ttf-parser/latest/ttf_parser/struct.Face.html#method.set_variation) method, is this method available from `ab_glyph`?

I'd like to reference https://lorp.github.io/samsa/src/samsa-gui.html which is a great tool for playing with font variations.

Thank you very much.

**Comment by alexheretic** [comment]
Hello, currently _ab_glyph_ hasn't exposed _ttf-parser_'s variable font methods.

That should be doable, a couple of things come to mind after a quick look:
* Having a `&mut self` method in _ab_glyph_ works less well with `FontArc` so perhaps a `fn with_variation(self, ...)` move approach would work better.
* The new methods would explicitly require _ttf-parser_ feature "variable-font" so we should probably add that (so it works in no-std) or expose it in ab-glyph as a feature too.
