### ISSUE TITLE
Issue with variable fonts (Link to issue in Bevy)

### ISSUE THREAD

**Issue by FarmingtonS9** [alexheretic/ab-glyph#62]
Hello all, found an issue using while using Bevy that involves using variable fonts. I'll link the issue from Bevy since all the info is there.
Issue: https://github.com/bevyengine/bevy/issues/5018

**Comment by alexheretic** [comment]
Hello, it looks like with this font glyph [glyph_hor_side_bearing](https://docs.rs/ttf-parser/latest/ttf_parser/struct.Face.html#method.glyph_hor_side_bearing) returns `None` which we don't currently expect to happen.

We need to figure out if
* this is a bug in ttf-parser behaviour
* a bug in this font
* or we should start handling `None` h side bearing here somehow (as 0?)

I'll do some investigation when i get a chance.

**Comment by alexheretic** [comment]
I've taken a look this morning and I think this can be fixed upstream: https://github.com/RazrFalcon/ttf-parser/issues/98

**Comment by alexheretic** [comment]
This has been fixed in _ttf-parser_ `0.15.2`. If you run `cargo update` all should be well.

**Comment by FarmingtonS9** [comment]
Yep, appears to work now. Thanks for the speedy update :)
