### ISSUE TITLE
Replacing `rusttype`

### ISSUE THREAD

**Issue by vbrandl** [alexheretic/ab-glyph#65]
I'm currently trying to replace the unmaintained [`rusttype`](https://crates.io/crates/rusttype) crate with `ab_glyph` but I don't really know what I'm doing...

I think I've got everything covered except one instance of the `Font::layout` method from `rusttype`: https://gitlab.redox-os.org/redox-os/rusttype/-/blob/master/src/font.rs#L191

How would you implement something like that method using ab_glyph?

**Comment by vbrandl** [comment]
Thanks, I'm only looking for single line layout. Your snippet helps a lot, now I just have to look into how I can calculate the width of the generated layout/vec

**Comment by alexheretic** [comment]
> how I can calculate the width

You can lookup an individual glyph's [`Font::glyph_bounds`](https://docs.rs/ab_glyph/latest/ab_glyph/trait.Font.html#method.glyph_bounds). So for a single line the difference between the first glyph's `min.x` and the last's `max.x` would give you a width based on layout info.
