### ISSUE TITLE
0.1.6 breaks no_std support

### ISSUE THREAD

**Issue by chxry** [alexheretic/ab-glyph#68]
since 0.1.6 uses `is_x86_feature_detected!`, the package no longer works with no_std

**Comment by alexheretic** [comment]
It would only affect target_arch x86 or x86_64 & I wasn't really aware of a no_std use case there. Can you provide a target that can no longer build that perhaps can be added to CI?

**Comment by alexheretic** [comment]
I guess its straightforward to address by requiring the `std` feature for any of the runtime detected simd.

**Comment by alexheretic** [comment]
I've published ab_glyph_rasterizer `0.1.7`.
