### ISSUE TITLE
This violates the original license of font-rs

### ISSUE THREAD

**Issue by mooman219** [alexheretic/ab-glyph#7]
This isn't "Inspired by font-rs & stb_truetype", it is the raster from font-rs with modifications. Please properly attribute, list changes, and license under Apache. After reading your blog post and reviewing the code, this feels extremely disingenuous.

If licensing is a pain for projects without re-used licensed code, consider using Zlib :D.

**Comment by alexheretic** [comment]
ab_glyph_rasterizer's **raster.rs** was forked from font-rs, I also copied stb_truetype code and converted it to handle cubic beziers. ab_glyph_rasterizer & font-rs are Apache 2.0 licensed, stb_truetype is MIT licensed so I believe this is explicitly permitted.

The top of the file says:
```
// Forked/repurposed from `font-rs` code: https://github.com/raphlinus/font-rs
// Cubic bezier drawing adapted from stb_truetype: https://github.com/nothings/stb
```
This seemed enough at the time, as it's the truth. Looking at the apache repackaging rules again, this file should probably have the original copyright too so I'll add that. MIT doesn't require that and so what I already have is sufficient.

**Comment by mooman219** [comment]
https://github.com/alexheretic/ab-glyph/commit/fcb1ab9f28d16b57b691b04742cf31ffe056eb0b

Looks better, thanks for updating it.
