### ISSUE TITLE
Handling of unexpected advance/side bearing values

### ISSUE THREAD

**Issue by yzsolt** [alexheretic/ab-glyph#70]
Currently the unscaled advance and side bearing getters in `ttfp.rs` expect that the underlying values exist.
I've run into a simple `v_side_bearing_unscaled()` panicking on me on a Times New Roman Italic TTF - I guess it's not a bug in the font. But even if it were, I think expect-ing these values is risky in a library depending on a parser, where the input files can sometimes be invalid(ish) but still generally usable. 
I think it'd make more sense to return 0.0 for these values instead, since doing so is harmless for the user, regardless if the values are absent either because the font or the TTF parser is buggy. What do you think?

**Comment by alexheretic** [comment]
i haven't seen an occurrence of this before which suggests it actually
could be a font bug.

I can't look closely right now, but i think i agree that returning zero
instead of panicking could be a pretty harmless way to address this in any
case.
