### ISSUE TITLE
Get vertical writing attribute

### ISSUE THREAD

**Issue by ekicyou** [alexheretic/ab-glyph#8]
I want a table reference API for vertical layout research.
If it's easy, I'll make a pull request.

> v_advance,  v_side_bearing, ...

Are there any plans to expand the layout API?
I would like to study it myself, so I would like to ask if you have any advice on extension points.

**Comment by alexheretic** [comment]
There are some vertical glyph metrics available (see https://docs.rs/ab_glyph/0.2.2/ab_glyph/trait.ScaleFont.html#method.ascent) but the API doesn't currently expose ttf-parser `glyph_ver_advance` etc. I don't really know how these are used as they don't apply to the kind layouts I need/needed.

However, I don't see why ab_glyph couldn't expose the `glyph_ver_*` equivalent methods in the same way it does `glyph_hor_*`. So I'd probably accept a pr with `v_advance` & `v_side_bearing`, and these should be straightforward to implement.

**Comment by ekicyou** [comment]
Thank you!
First, consider pr.
Next, I think we need to investigate the value returned by the API.
