### ISSUE TITLE
Coverage out of `[0, 1`] range

### ISSUE THREAD

**Issue by e00E** [alexheretic/ab-glyph#84]
I have observed `OutlinedGlyph::draw` call my callback with a coverage of `1.0000001`. This goes against the documentation, which says "with a coverage value in the range `[0.0, 1.0]`". This is likely due to floating point error.

I see two ways of addressing the problem:
1. Document that the value is supposed to be in this range but might sometimes be outside. The user needs to clamp it if the exact range is important.
2. Clamp the value in ab-glyph like with `coverage.clamp(0.0, 1.0)`.

I can give a full reproduction if required.

**Comment by alexheretic** [comment]
If the docs are saying that then yes they should be updated. Clamping was removed in [_ab_glyph_rasterizer_ 0.1.5](https://github.com/alexheretic/ab-glyph/blob/main/rasterizer/CHANGELOG.md#015)

**Comment by e00E** [comment]
Thanks. The problematic documentation is [here](https://github.com/alexheretic/ab-glyph/blob/abbe81f3addecfc9af3f20494d1e6a8996f2afba/glyph/src/outlined.rs#L89) btw.

**Comment by alexheretic** [comment]
Thanks for reporting this :+1:
