### ISSUE TITLE
How can i get the bearing information for text rendering? 

### ISSUE THREAD

**Issue by sry948749099** [alexheretic/ab-glyph#85]
Now, this crate could only get the offset from baseline to left of glyph, but i want to know how to get the offset from baseline to top of glyph, Please let me know at your convenience what interface i should call

**Comment by alexheretic** [comment]
Do you mean [ascent](https://docs.rs/ab_glyph/latest/ab_glyph/trait.ScaleFont.html#method.ascent)?

![](https://user-images.githubusercontent.com/6064962/88629913-71e15300-d0e2-11ea-93cc-9a7a49a96906.png)

**Comment by sry948749099** [comment]
> Do you mean [ascent](https://docs.rs/ab_glyph/latest/ab_glyph/trait.ScaleFont.html#method.ascent)?
> 
> ![](https://user-images.githubusercontent.com/6064962/88629913-71e15300-d0e2-11ea-93cc-9a7a49a96906.png)

thanks for your reply
I don't think it's ascent, because ascent in ab glyph crate doesn't depend on glyph id, but all glyph are the same

**Comment by alexheretic** [comment]
Ascent is generally what you use for layout kind of work. What do you need the per-glyph height for? Rasterization?

**Comment by sry948749099** [comment]
> Ascent is generally what you use for layout kind of work. What do you need the per-glyph height for? Rasterization?

find the baseline of this glyph, by the way to get the rectangle coords of each glyph for text rendering.

**Comment by alexheretic** [comment]
> find the baseline of this glyph, by the way to get the rectangle coords of each glyph for text rendering.

I'm not 100% understanding your questions. 

But related to rendering, to render you first [outline](https://docs.rs/ab_glyph/0.2.21/ab_glyph/trait.ScaleFont.html#method.outline_glyph) the glyph. From that you can draw all pixels. The outlined glyph also provides the [`OutlinedGlyph::px_bounds`](https://docs.rs/ab_glyph/0.2.21/ab_glyph/struct.OutlinedGlyph.html#method.px_bounds) a rectangle covering the glyph's pixels. This is perhaps what you are looking for?

The [image example](https://github.com/alexheretic/ab-glyph/blob/main/dev/examples/image.rs#L54) demonstrates usage.
