### ISSUE TITLE
Width and height info are not exposed in `GlyphImage`

### ISSUE THREAD

**Issue by EHfive** [alexheretic/ab-glyph#86]
For image in `GlyphImageFormat::Png` format, it's possible to decode width and height info from PNG header in data.
But for other `GlyphImageFormat::Bitmap*` formats, it's not possible to index bitmap data by 2D position without width info at least.

Also the height info is needed to calculate origin position for pixel drawing.

**Comment by alexheretic** [comment]
w+h are provided [upstream](https://docs.rs/ttf-parser/latest/ttf_parser/struct.RasterGlyphImage.html) I'm not sure why they were omitted here, perhaps they were added upstream later? 

We should add them here, though it looks like it may be a breaking change 😕. Raise a pr and we can figure out the best approach.
