### ISSUE TITLE
Custom font colors

### ISSUE THREAD

**Issue by morn-0** [alexheretic/ab-glyph#93]
my context: it's based on a tiny-skia pixmap getting pixels_mut for the operation.
Hello, I am trying to customize the rendering color of a font. I've tried a few options and they don't seem to work very well

**Comment by alexheretic** [comment]
The ab_glyph rasterizer provides just coverage values for each pixel. You can colour them any way you like.

For instance, the [image example](https://github.com/alexheretic/ab-glyph/blob/main/dev/examples/image.rs) colours the glyphs dark red.

**Comment by morn-0** [comment]
![image](https://github.com/alexheretic/ab-glyph/assets/90960002/fe3167fd-1b45-483c-9477-faf8eb778e24)
![image](https://github.com/alexheretic/ab-glyph/assets/90960002/bd26aa84-446d-4502-ae19-01ddc31f7978)

use color(150, 0, 0); maybe not work

**Comment by morn-0** [comment]
i use [tiny-skia](https://github.com/RazrFalcon/tiny-skia)

**Comment by alexheretic** [comment]
> i use [tiny-skia](https://github.com/RazrFalcon/tiny-skia)

I'm not familiar with that lib myself. But as long you are getting the correct coverage values for the glyphs I don't think this is an issue for ab_glyph.
