### ISSUE TITLE
Get the associated `char` of a `GlyphId`

### ISSUE THREAD

**Issue by indietyp** [alexheretic/ab-glyph#96]
I am currently trying to determine if a character is supposed to be a whitespace, to do so I currently need to do:

```
self.font
            .codepoint_ids()
            .find_map(|(id, char)| {
                if id == self.glyph.id {
                    Some(char)
                } else {
                    None
                }
            })
            .map_or(false, |char| char.is_whitespace())
```

I know that there is a specific function to map from `char -> GlyphId`, does a reverse exist that doesn't need to go through the iterator every time?

**Comment by alexheretic** [comment]
You can collect the codepoint_ids into a map to provide that.

You could also track this when you get the GlyphId to begin with.

**Comment by indietyp** [comment]
Thank you! I thought that there might've been a more straightforward way to do this, but after looking a bit in `ttf_parser`, this doesn't seem to be the case.
